version: "3.4"
services:
  mq:
    image: rabbitmq:3.7-management-alpine
    hostname: test-rabbit
    volumes:
      - ./.rabbit_data:/var/lib/rabbitmq
    ports:
      - '15672:15672'
      - '5672:5672'

  db:
    image: postgres:11.5-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'project'
      POSTGRES_PASSWORD: '123'
      POSTGRES_DB: 'project'
    volumes:
      - ./.postgres_data:/var/lib/postgresql/data

  cache:
    image: redis:6.2-alpine
    command: redis-server --appendonly yes
    environment:
      PORT: 6380
      PASS: 123
    ports:
      - '6380:6380'
    volumes:
      - ./.redis_data:/data

  proxy:
    image: nginx:1.19.10-alpine
    ports:
      - '8000:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: Dockerfile
